---
version: '3.7'

# environment values are loaded from .env

secrets:
  opc_yml:
    file: opc.yml

services:
  opc:
    build:
      context: .
      args:
        - OPC_UID=777
    image: opc
    command: "--debug"
    volumes:
      - ./opc:/usr/src/opc/opc
      - ./plugins:/home/opc/plugins
      - ./layouts:/home/opc/layouts
      - ./opc.yml:/home/opc/opc.yml
    secrets:
      - source: opc_yml
